### ISSUE TITLE
Sync with latest version of the upstream lib

### ISSUE THREAD

**Issue by brunomvsouza** [brunomvsouza/singleflight#3]
Current version is 0.6.0. See https://pkg.go.dev/golang.org/x/sync/singleflight?tab=versions.

**Comment by karelbilek** [comment]
ping

**Comment by karelbilek** [comment]
btw why do you reimplement the whole thing instead of "just" wrapping sync/singleflight? I think that would be easier?

**Comment by brunomvsouza** [comment]
@karelbilek Thank you for your suggestion. The current implementation suits my purposes better.
